# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The ProtProtocols project
description: >- # this means to ignore newlines until "baseurl:"
  The ProtProtocols project creates reproducible, simple-to-use bioinformatic
  workflows for common proteomics workflows. The protocols are shipped as docker
  containers in order to make them reproducible and as easy as possible to install.
  The protocols are then launched as Jupyter notebooks within the containers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username: ProtProtocols

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
#remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

# Exclude from processing.
# The following itemms will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md

# Default layouts, etc.
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "single"
    -
        scope:
            path: "_pages/documentation_pages"
            type: "pages"
        values:
            toc: true
            toc_label: "On this page"
            header:
                overlay_image: /assets/images/alfons-morales-410757-unsplash.jpg
                overlay_filter: 0.5
                caption: "Photo by [Alfons Morales](https://unsplash.com/photos/YLSwjSy7stw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/search/photos/book?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)"
                actions:
                    - label: "<i class='fas fa-question-circle'></i> Get help"
                      url: "http://qa.proteomics-academy.org"
            excerpt: "For additional help, simply post on the EuBIC bioinformatics mailing list."
            sidebar:
                nav: doc_toc



